temporalio/temporalite

cmd/temporalite/main.go
internal/liteconfig/config.go
options.go
server.go

I'm adding a new server option `WithUpstreamOptions(options ...temporal.ServerOption)` enabling users to configure the Temporal server more granularly., e.g.:
```golang
opts := []temporalite.ServerOption{
temporalite.WithNamespaces("default"),
temporalite.WithDynamicPorts(),
temporalite.WithPersistenceDisabled(),
temporalite.WithUpstreamOptions(
temporal.ForServices([]string{primitives.FrontendService}),
),
}
srv, err := temporalite.NewServer(opts...)
```
**Why?**
This allows users configuring all server options, like [InterruptOn](`https://docs.temporal.io/docs/server/options/#interrupton`), without the maintenance burden of having dedicated functions.
Tested locally.
This is a backward incompatible change. Before, …

Add WithUpstreamOptions server option

---

server.go

Exposed `FrontendHostPort`
**Why?**
Some uses of temporalite may want to use this value for their own client creation, or in my case, pass it somewhere else for their use.
Ideally this would be `FrontendAddr() net.Addr` and the system would support things like local unix paths and such, but I understand this is a Temporal server limitation too. I also considered just exposing `FrontendPort` since `127.0.0.1` is hardcoded, but I assumed it may not be hardcoded always and `host:port` can be directly passed to different forms of `Dial`.
Untested getter.
None
No

Expose frontend host:port

---

cmd/temporalite/main.go
internal/liteconfig/config.go
options.go

Adding an optional flag to bind frontend to an IP address instead of localhost.
**Why?**
In order to expose the frontend service from a docker container.
Locally using https://github.com/jbreiding/potential-goggles
Optional flag
No

Add optional flag to bind frontend ip address

---

go.mod
go.sum

This PR changes the dependency on Tally to use v4.1.0, this is to solve issue #18. I did run the tests as the workflow explains to ensure it still compiles and passes the tests.
I do not see any potential risks on this PR besides being able to import the temporalite go library (which is where we are now according to the issue).
I would say it is a candidate for hotfix, not sure that this impacts other communities.

changes tally to use v4.1.0

---

temporaltest/options.go
temporaltest/server.go
temporaltest/server_test.go

Test servers now are automatically shut down after the parent test case completes via [T.Cleanup](https://pkg.go.dev/testing#T.Cleanup).
**Why?**
This reduces the boilerplate needed to set up and tear down test servers.
Verified by logging in the cleanup function and running tests.
Folks might not want to tie test server lifecycle to a single Go test. In this case table tests or not passing the `WithT` option may be a better fit.

Automatically stop server after test completion via T.Cleanup

---

README.md

Presented at the Temporal meetup on November 23rd 2021: https://youtu.be/Hz7ZZzafBoE

Link to Temporalite intro & demo video

---

Dockerfile

Adding Dockerfile for demo purposes with temporal ui
Adding a Dockerfile for local development
**Why?**
Setting up a local development environment using
https://github.com/jbreiding/potential-goggles
To work on and demo both code bases.
docker and docker-compose
vscode devcontainers
GH codespaces
``` sh
$ docker build -t temporalite:testv2 . --no-cache
$ docker run temporalite:testv2
```
None
No.

Add Dockerfile to support running in a container

---

cmd/temporalite/main.go

Updates the `temporalite` CLI to always use dynamic ports.
**Why?**
Previously ports for internal APIs were assigned by adding a hardcoded offset to the frontend grpc port. About 10 ports are computed in this way, leading to a high chance of conflicts.
Closes #34.
Some users may have been depending on the previous behavior, since pprof and metrics ports were predictable (though this was never documented). Explicit flags for setting those ports can be added later.
No

Use dynamic ports from CLI

---

.github/workflows/ci.yml
README.md
cmd/temporalite/main.go
cmd/temporalite/ui.go
cmd/temporalite/ui_disabled.go
cmd/temporalite/ui_disabled_test.go
cmd/temporalite/ui_test.go

Closes https://github.com/DataDog/temporalite/issues/33
**Why?**
Temporalite isn't always used in environments where a web UI is required or desired. Adding a build tag to disable the web UI is also a mitigation for https://github.com/DataDog/temporalite/issues/46.
Added a unit test to ensure that the ui-server package is not part of the dependency graph when the `headless` build tag is specified, and also added this build tag to the test matrix in CI.
No

Disable web UI via build tag or runtime flag

---

cmd/temporalite/main.go
internal/liteconfig/config.go

Adding an optional flag to set log level.
**Why?**
Closes #57 
go run ./cmd/temporalite/ start --ephemeral --log-level=info
go run ./cmd/temporalite/ start --ephemeral --log-level=debug
go run ./cmd/temporalite/ start --ephemeral --log-level=info --log-format=pretty
go run ./cmd/temporalite/ start --ephemeral --log-level=debug --log-format=pretty
go run ./cmd/temporalite/ start --ephemeral 
log level default (if omitted) is changed to info from debug
no

fix: log level support

---

cmd/temporalite/main.go
internal/liteconfig/config.go
options.go

Added command line flag to set the metrics port.
**Why?**
Without this temporalite is not easily useable in situations where users would like to scrape the metrics.
Ran with `--metrics-port ..` and check that I could scrape on the expected port.
None. Default behaviour remains as it was.
No.

Add --metrics-port flag.

---

.github/workflows/ci.yml

Now that CGO is no longer a requirement of the SQLite driver, we can enable tests with CGO disabled in CI.
**Why?**
Validate that Temporalite works in environments where CGO is not available.
CI
None
No

Test with CGO disabled

---

temporaltest/server.go

This PR removes previously deprecated `Worker` and `Client` methods from the `temporaltest` package, which were replaced by `NewWorker` and `DefaultClient` respectively.
**Why?**
We're cutting a semantically versioned release soon and this avoids a future breaking change to remove deprecated APIs.
N/A
There may be existing consumers of these APIs; they will need to modify their source code before upgrading to the first official release.
No

Remove deprecated Worker and Client methods

---

.vscode/launch.json
README.md

Adds a debug script for vscode
**Why?**
simpler to debug temporalite (F5)

Add vscode debug script

---

README.md
go.mod
go.sum

Fixes escaping of special URL symbols
**Why?**
Resolves #117  
Verified with a workflow id that has spaces, /, %, /, \ etc <https://github.com/minimaxir/big-list-of-naughty-strings>

Fix UI escaping special symbols

---

internal/copyright/header.txt
internal/copyright/main.go

We changed the license header, and this broke the copyright verification tool. This fixes that bug and also removes a now unused header file.

Fix copyright header verification mode

---

README.md
cmd/temporalite/main.go
cmd/temporalite/main_test.go
internal/liteconfig/config.go
options.go
server.go
temporaltest/server.go
temporaltest/server_test.go

* Added CLI and library support for setting individual dynamic config values
* Defaulted CLI (with opt-out) and test server to disable search attribute cache
**Why?**
For use with search attributes, the dev-only setting to disable cache is needed or there is a wait period before the search attributes are available for use.
This further cements that Temporalite is not for production use. This is the same config as dev docker compose at https://github.com/temporalio/docker-compose/blob/7c4f708c579cd735145e49816750ca4368ff5bf3/dynamicconfig/development-sql.yaml#L5. Any concerns here?

Set dynamic config values and default search attribute cache as disabled

---

cmd/temporalite/main.go
cmd/temporalite/mtls_test.go
cmd/temporalite/testdata/temporalite-ui.yaml
cmd/temporalite/ui.go
cmd/temporalite/ui_disabled.go
cmd/temporalite/ui_test.go
internal/examples/mtls/temporalite-ui.yaml.template

Two changes:
1. Allow temporal web/ui to be configured from a yaml file so that the web UI does not break when the API is configured for mTLS.
2. Since the UI cannot be run via HTTPS, allow the UI to be bound to a different IP than the API. This can facilitate the API with mTLS being exposed to non-local clients, while keeping the UI available to localhost.
**Why?**
Temporalite is great, and I want to use it safely in situations where I'm experimenting with mTLS in temporal, especially while implementing mTLS in workers, without the UI being broken.
Ran temporalite locally without any TLS, and with TLS certificates created by a self-signed root CA. The latter required the creation of temporalite.yaml and temporalite-ui.yaml files in a …

allow web UI to be configured when using mTLS in API

---

README.md
cmd/temporalite/main.go

fix: Ensures directory path to db file exists

---

cmd/temporalite/main.go
cmd/temporalite/main_test.go
cmd/temporalite/mtls_test.go
internal/liteconfig/config.go
internal/liteconfig/freeport.go
temporaltest/server.go
temporaltest/server_test.go

This PR adds test cases for creating the default data directory when it doesn't already exist, returning an error when a custom db path is configured in a missing directory, and starting the server with a custom db path in an existing directory.
I've also removed panic logs in integration tests and increased timeouts in an attempt to decrease test flakiness. This was done with a new `--log-format noop` flag value.
**Why?**
This is basic behavior that I believe should be validated with an integration test. The test case for starting Temporal server with a default db path will also catch any breaking change that updates the default path.
CI
I noticed a whole host of race conditions in the integration tests during development. …

Test creating default db directory

---

README.md

Changed install instructions to use releases instead of `go install`
**Why?**
Since #118, this is now displayed on `go install`:
```
go: github.com/temporalio/temporalite/cmd/temporalite@latest (in github.com/temporalio/temporalite@v0.2.0):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```

Remove "go install" README instructions

---

cmd/temporalite/main.go
cmd/temporalite/ui.go
cmd/temporalite/ui_disabled.go
cmd/temporalite/ui_test.go

This allows starting a temporalite instance with a remote data converter endpoint preconfigured.
Adds a new `--ui-codec-endpoint` flag to `temporalite start`.
**Why?**
Exposing the flag allows to send a single command to run to users that can rely on a remote data converter hosted somewhere instead of telling them to run 2 processes on their laptop.
Manually
None
No

Expose a new --codec-endpoint flag to start command
